#################
### AUTOSTART ###
#################

exec-once = hyprlock
exec-once = QS_ICON_THEME="Cosmic" quickshell
exec-once = awww-daemon
exec-once = hyprctl setcursor Bibata-Modern-Classic 22
