-- Generated by Matugen. Changes to this file will be overwritten.
local colors = {

    background = "rgb(1a1110)",

    error = "rgb(ff5449)",

    error_container = "rgb(7b0007)",

    inverse_on_surface = "rgb(6f615f)",

    inverse_primary = "rgb(b96c5c)",

    inverse_surface = "rgb(f1dfdb)",

    on_background = "rgb(6d5f5d)",

    on_error = "rgb(5c0003)",

    on_error_container = "rgb(ff7d70)",

    on_primary = "rgb(703226)",

    on_primary_container = "rgb(e28e7d)",

    on_primary_fixed = "rgb(ffb1a1)",

    on_primary_fixed_variant = "rgb(dd8a79)",

    on_secondary = "rgb(3d231e)",

    on_secondary_container = "rgb(c29b93)",

    on_secondary_fixed = "rgb(e4bab2)",

    on_secondary_fixed_variant = "rgb(be978f)",

    on_surface = "rgb(af9f9c)",

    on_surface_variant = "rgb(927f7b)",

    on_tertiary = "rgb(352800)",

    on_tertiary_container = "rgb(b8a26d)",

    on_tertiary_fixed = "rgb(d9c28a)",

    on_tertiary_fixed_variant = "rgb(b49e69)",

    outline = "rgb(61504d)",

    outline_variant = "rgb(453734)",

    primary = "rgb(cc7b6b)",

    primary_container = "rgb(63281c)",

    primary_fixed = "rgb(7f3e31)",

    primary_fixed_dim = "rgb(63281c)",

    scrim = "rgb(000000)",

    secondary = "rgb(ae8880)",

    secondary_container = "rgb(4f332d)",

    secondary_fixed = "rgb(694943)",

    secondary_fixed_dim = "rgb(4f332d)",

    shadow = "rgb(000000)",

    source_color = "rgb(e53211)",

    surface = "rgb(1a1110)",

    surface_bright = "rgb(423734)",

    surface_container = "rgb(271d1b)",

    surface_container_high = "rgb(322826)",

    surface_container_highest = "rgb(3d3230)",

    surface_container_low = "rgb(231918)",

    surface_container_lowest = "rgb(140c0b)",

    surface_dim = "rgb(1a1110)",

    surface_tint = "rgb(ffb4a5)",

    surface_variant = "rgb(534340)",

    tertiary = "rgb(a38f5b)",

    tertiary_container = "rgb(47380d)",

    tertiary_fixed = "rgb(604f22)",

    tertiary_fixed_dim = "rgb(47380d)",

}

return colors
