#   ▖▖▖▖▄▖▄▖▖ ▄▖▖ ▖▄   ▄▖▄▖▖ ▖▄▖▄▖▄▖   #
#   ▙▌▌▌▙▌▙▘▌ ▌▌▛▖▌▌▌  ▌ ▌▌▛▖▌▙▖▐ ▌    #   
#   ▌▌▐ ▌ ▌▌▙▖▛▌▌▝▌▙▘  ▙▖▙▌▌▝▌▌ ▟▖▙▌   #
#                                  -DK #
                                
# environment variables
source = ~/.config/hypr/environment.conf

# nvidia gpu settings
source = ~/.config/hypr/nvidia.conf

# monitor configuration
source = ~/.config/hypr/monitors.conf

# programs and launcher config
source = ~/.config/hypr/programs.conf

# applications to start on login
source = ~/.config/hypr/autostart.conf

# colors from pywal theme
source = ~/.cache/wal/hyprland-pywal.conf

# window style and layout rules
source = ~/.config/hypr/style-layout.conf

# input devices and settings
source = ~/.config/hypr/input.conf

# keyboard shortcuts
source = ~/.config/hypr/keybinds.conf

# window rules for specific apps
source = ~/.config/hypr/windowrules.conf
