################
### MONITORS ###
################
# TODO I need to make this part more dynamic in the future, pluggin and uplugging monitors seems off.

#monitor = ${hyprctl monitors all  | awk '/Monitor/ {print $2}' | head -n 1}, 1920x1080@60, 0x0, 1
#monitor = eDP-1, 1920x1080@160, 0x0, 1
#monitor = DP-2, 1920x1080@100, 0x-1080, 1
#monitor = DP-3, 1920x1080@60, 1920-1080, 1, transform, 3 
#monitor = HDMI-A-1, 1920x1080@60, -1080x-1080, 1, transform, 1 
monitor = ,1920x1080@60, auto-right, 1
