###################
#### PROGRAMS  ####
###################

$terminal = kitty
$fileManager = cosmic-files 
$menu = wofi --show drun
$shape-theme = ~/Desktop/shape-theme/theme-menu.sh
$shape-theme-fill = ~/Desktop/shape-theme/change-theme-menu-wallcrop.sh
