###################
### WINDOWRULES ###
###################

windowrule = animation slide, match:class kitty # sets the animation style for kitty
windowrule = opacity 0.8 0.8, match:class kitty
windowrule = opacity 0.9 0.9, match:class vscodium
windowrule = float on, match:title LibrePods
windowrule = size 300 300, match:title LibrePods
windowrule = center on, match:title LibrePods
windowrule = suppress_event maximize, match:class .* # You'll probably like this.
