-- Generated by Matugen. Changes to this file will be overwritten.
local colors = {
<* for name, value in colors *>
    {{ name }} = "rgb({{ value.default.hex_stripped }})",
<* endfor *>
}

return colors
