pragma Singleton

import Quickshell
import QtQuick

Singleton {
    id: root

    readonly property string wallrustWallpaper: "/home/Gandalf/Wallpapers/spacefix.jpg"
    readonly property string wallrustMode: "dark"
    readonly property string wallrustName: "spacefix.jpg"

    readonly property DynamicColors palette: DynamicColors {}

    component DynamicColors: QtObject {

	    <* for name, value in colors *>
	    	readonly property color {{name}}: "{{value.default.hex}}"
	    <* endfor *>
       
    }
}
