#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-A-0 -d  VI VII VIII IX X
#bspc monitor eDP -d I II III IV V

# Configure Monitors ==========================================================
# Found here: https://github.com/wmilou/bspwmporn/blob/main/bspwm/bspwmrc
# Adapted by me

#Configs side of monitors BSPWM
SECOND_MONITOR_SIDE="left"
THIRD_MONITOR_SIDE="right"

#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep -w connected | awk '{i++}i==2'| awk '{print $1}')
THIRD_MONITOR=$(xrandr | grep  -w connected | awk '{i++}i==3'| awk '{print $1}')


# Code to activate Displaylink DVI monitors (possible bug workaround)
if xrandr | grep DVI; then
   xrandr --ourput $PRINCIPAL --mode 1920x1080
   
   xrandr | grep DVI | awk '{print $1}'| \
   xargs -I screen xrandr --output screen --mode 1920x1080
 
   sleep 5
fi

if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "3" ]; then
  #.screenlayout/cepes.sh
  bspc monitor $(bspc query -M --names | sed -n 1p) -d 1 2 3
  bspc monitor $(bspc query -M --names | sed -n 2p) -d 4 5 6 7
  bspc monitor $(bspc query -M --names | sed -n 3p) -d 8 9 10
  # #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
  xrandr --output $THIRD_MONITOR --$THIRD_MONITOR_SIDE-of $PRINCIPAL  
elif [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d 1 2 3 4 5
  bspc monitor $(bspc query -M | sed -n 2p) -d 6 7 8 9 10
  #Set Monitors Side and output 
  SECOND_MONITOR_SIDE="left"
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi


# Border Colors ===============================================================

bspc config normal_border_color \#81aeb6
bspc config active_border_color \#81aeb6
bspc config focused_border_color \#bf4c39

# Rules =======================================================================

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Tk state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
# Script for multiple screens
# found here https://github.com/polybar/polybar/issues/763
#$HOME/.config/polybar/launch_polybar.sh

nitrogen --restore
xsetroot -cursor_name heart
setxkbmap -model abnt2 -layout br -variant abnt2
picom --config .config/picom/picom.conf